### ISSUE TITLE
Compatibility issue with AuthorizationChecker

### ISSUE THREAD

**Issue by Tiriel** [elephantly/kahlan-bundle#2]
When testing and using symfony's built in security.authorization_checker service, following error prevents test suite from running:

`an uncaught exception has been thrown in `/tmp/kahlanvendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/ExpressionLanguageProvider.php` line 55
      
      message:`ParseError` Code(0) with message "syntax error, unexpected ','"
      
        [NA] - /tmp/kahlan/home/benjamin/Documents/Dev/www/morpheus/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/ExpressionLanguageProvider.php, line 51 to 55`

Services using security.authorization_checker are not instanciated and thus not fit for testing. Need to find correct settings.

**Comment by Tiriel** [comment]
This seems to be in fact a very specific problem to one particular installation.
I can't reproduce the problem in a new installation, instanciation of security.authorization_checker works just fine.
Closing issue tomorrow if no other information is found.

**Comment by jails** [comment]
Next time you get stuck on such syntax error issue, feel free to open an issue in the kahlan repo with the code indicated by the error (i.e the one in `/tmp/kahlan/`) and the corresponding code in the `src` directory (just lines 51 to 55 for both files in this case). 
Kahlan performs some Just In Time code patching so sometimes the generated patch is just wrong.
A similar error happening with PHP<7 has been fixed in 3.1.0, so it may be related.

**Comment by Tiriel** [comment]
Might indeed be worth checking. I'll just re run my tests and see if I still got the issue. If it comes from Kahlan's tmp files, I'll open an issue then.

Thanks for the tip!

**Comment by Tiriel** [comment]
Just to let you know, I think it was the same bug. By running `composer update` in the faulty project, I upgraded to kahlan 3.1.0 and problem disapeared. Thanks!
